"""
Module: board.py
Description: Board router — starts debate session, streams debate updates via SSE,
             and provides session history for replaying past debates.

Author:  KAIRON / Founder Twin
Created: 2025-06-09
"""

import uuid
import json
import asyncio
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from models.board import BoardSession, BoardDecision
from models.founder import DigitalTwin
from core.debate_engine import run_debate
from core.decision_synthesizer import synthesize_decision
from services.mongodb_service import MongoDBService
from utils.logger import get_logger
from utils.errors import DebateError, SynthesisError

logger = get_logger(__name__)
router = APIRouter(prefix="/board", tags=["board"])
db = MongoDBService()


class StartDebateRequest(BaseModel):
    twin_id: str


async def _run_debate_background_task(session: BoardSession, twin: DigitalTwin):
    try:
        session = await run_debate(session, twin)
        await db.save_session(session)
        decision = await synthesize_decision(session, twin)
        session.decision = decision
        session.status = "decided"
        await db.save_session(session)
        logger.info("Background board session complete", extra={"session_id": session.session_id})
    except Exception as e:
        logger.error("Background board session failed", extra={"error": str(e)})
        session.status = "failed"
        await db.save_session(session)


@router.post("/start", response_model=BoardSession)
async def start_debate(request: StartDebateRequest, background_tasks: BackgroundTasks) -> BoardSession:
    """
    Initialize a board debate and start it in the background.

    Args:
        request: Contains twin_id to load the founder's DigitalTwin.

    Returns:
        BoardSession with status 'debating'.
    """
    twin: DigitalTwin | None = await db.get_twin(request.twin_id)
    if not twin:
        raise HTTPException(status_code=404, detail=f"Twin '{request.twin_id}' not found")

    session = BoardSession(
        session_id=str(uuid.uuid4()),
        twin_id=request.twin_id,
        status="debating",
        created_at=datetime.now(timezone.utc).isoformat(),
    )
    await db.save_session(session)
    logger.info("Board session initialized", extra={"session_id": session.session_id})

    background_tasks.add_task(_run_debate_background_task, session, twin)
    return session


@router.get("/sessions/{twin_id}")
async def list_sessions(twin_id: str) -> list[dict]:
    """
    Return a summary list of all past board sessions for a twin.
    Used for the session history / replay panel.
    """
    sessions = await db.get_sessions_for_twin(twin_id)
    result = []
    for s in sessions:
        result.append({
            "session_id": s.session_id,
            "status": s.status,
            "created_at": getattr(s, "created_at", None),
            "decision": s.decision.decision if s.decision else None,
            "overall_score": s.decision.overall_score if s.decision else None,
            "viability_score": s.decision.viability_score if s.decision else None,
            "founder_fit_score": s.decision.founder_fit_score if s.decision else None,
            "key_insight": s.decision.key_insight if s.decision else None,
            "original_idea": s.decision.original_idea if s.decision else None,
        })
    result.sort(key=lambda x: x.get("created_at") or "", reverse=True)
    return result


@router.get("/session/{session_id}")
async def get_session_detail(session_id: str) -> dict:
    """
    Return full session detail including all rounds, opinions, decision, and execution package.
    Used for replaying a past board session.
    """
    session = await db.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    package = await db.get_execution_package(session_id)

    return {
        "session": session.model_dump(),
        "execution_package": package.model_dump() if package else None,
    }


@router.get("/{session_id}/stream")
async def stream_debate(session_id: str) -> StreamingResponse:
    """
    Stream debate updates for a session as Server-Sent Events.

    Used by the frontend BoardRoom to show the debate live.
    Polls the database for new opinions generated by the background task.

    Args:
        session_id: Board session ID to stream.

    Returns:
        StreamingResponse with SSE-formatted debate events.
    """
    async def event_generator():
        yielded_opinions = set()

        while True:
            session: BoardSession | None = await db.get_session(session_id)
            if not session:
                yield f"data: {json.dumps({'error': 'Session not found'})}\n\n"
                return

            # Yield any new opinions
            for round_idx, round_opinions in enumerate(session.rounds, start=1):
                for opinion in round_opinions:
                    op_id = f"{round_idx}-{opinion.agent.value}"
                    if op_id not in yielded_opinions:
                        payload = opinion.model_dump()
                        payload["round_label"] = {
                            1: "ROUND 1 — INITIAL POSITIONS",
                            2: "ROUND 2 — CROSS-EXAMINATION",
                            3: "ROUND 3 — FINAL VOTE",
                        }.get(round_idx, f"ROUND {round_idx}")
                        yield f"data: {json.dumps(payload)}\n\n"
                        yielded_opinions.add(op_id)
                        await asyncio.sleep(0.4)  # Dramatic pacing

            if session.status == "decided":
                if session.decision:
                    yield f"data: {json.dumps({'type': 'decision', 'data': session.decision.model_dump()})}\n\n"
                yield "data: [DONE]\n\n"
                break

            if session.status == "failed":
                yield f"data: {json.dumps({'error': 'Debate failed during execution'})}\n\n"
                yield "data: [DONE]\n\n"
                break

            await asyncio.sleep(1.0)  # Poll every 1 second

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive"
        },
    )
